CREATE TABLE TB_CLIENTES (
    CPF VARCHAR2(11),
    NOME VARCHAR2(100),
    ENDERECO1 VARCHAR2(150),
    ENDERECO2 VARCHAR2(150),
    BAIRRO VARCHAR2(50),
    CIDADE VARCHAR2(50),
    ESTADO VARCHAR2(2),
    CEP VARCHAR2(8),
    IDADE INT,
    SEXO VARCHAR2(1),
    LIMITE_CREDITO FLOAT,
    VOLUME_COMPRA FLOAT,
    PRIMEIRA_COMPRA NUMBER(1)
);

CREATE TABLE TABELA_DE_VENDEDORES (
    MATRICULA VARCHAR2(5),
    NOME VARCHAR2(100),
    PERCENTUAL_COMISSAO FLOAT
);

ALTER TABLE TABELA_DE_VENDEDORES ADD CONSTRAINT PK_TABELA_DE_VENDEDORES PRIMARY KEY (MATRICULA);

CREATE TABLE TB_PRODUTOS (
    PRODUTO VARCHAR2(20),
    NOME VARCHAR2(150),
    EMBALAGEM VARCHAR2(50),
    TAMANHO VARCHAR2(50),
    SABOR VARCHAR2(50),
    PRECO_LISTA FLOAT
);

INSERT INTO TB_PRODUTOS (
    PRODUTO,
    NOME,
    EMBALAGEM,
    TAMANHO,
    SABOR,
    PRECO_LISTA
)
VALUES (
    '1040107',
    'Light - 350 ml - Melancia',
    'Lata',
    '350 ml',
    'Melancia',
    4.56
);

SELECT * FROM TB_PRODUTOS;

INSERT INTO TABELA_DE_VENDEDORES (
    MATRICULA,
    NOME,
    PERCENTUAL_COMISSAO
) VALUES (
    '00233',
    'José Geraldo da Fonseca',
    0.10
);

SELECT * FROM TABELA_DE_VENDEDORES;

INSERT INTO TB_PRODUTOS (
    PRODUTO,
    NOME,
    EMBALAGEM,
    TAMANHO,
    SABOR,
    PRECO_LISTA
) VALUES (
    '1037797',
    'Clean - 2 Litros - Laranja',
    'PET',
    '2 Litros',
    'Laranja',
    16.01
);

INSERT INTO TB_PRODUTOS (
    PRODUTO,
    NOME,
    EMBALAGEM,
    TAMANHO,
    SABOR,
    PRECO_LISTA
) VALUES (
    '1000889',
    'Sabor da Montanha - 700 ml - Uva',
    'Garrafa',
    '700 ml',
    'Uva',
    6.31
);

INSERT INTO TB_PRODUTOS (
    PRODUTO,
    NOME,
    EMBALAGEM,
    TAMANHO,
    SABOR,
    PRECO_LISTA
) VALUES (
    '1004327',
    'Videira do Campo - 1,5 Litros - Melancia',
    'PET',
    '1,5 Litros',
    'Melancia',
    19.51
);

SELECT * FROM TB_PRODUTOS;

INSERT INTO TABELA_DE_VENDEDORES (
    MATRICULA,
    NOME,
    PERCENTUAL_COMISSAO
) VALUES (
    '00235',
    'Márcio Almeida Silva',
    0.08
);

INSERT INTO TABELA_DE_VENDEDORES (
    MATRICULA,
    NOME,
    PERCENTUAL_COMISSAO
) VALUES (
    '00236',
    'Cláudia Morais',
    0.08
);

SELECT * FROM TABELA_DE_VENDEDORES;